services:
  bot:
    container_name: bot-scan
    image: bot-scan:latest
    depends_on:
      - websearch
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore: 
            - ./node_modules/
        - action: rebuild
          path: package.json
          target: /app/package.json
        # - action: sync+restart
        #   path: /src/bot.ts
        #   target: /app/dist/bot.js
    ports:
      - "3003:3003"
    
  websearch:
    container_name: websearch
    build:
      context: ./webSearch
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
